### ISSUE TITLE
REQUEST DNS TXT KEY 

### ISSUE THREAD

**Issue by rialdytrike** [FIVEJACK/itemku-seller-open-api#1]
Halo saya ingin meminta dns txt key untuk verifikasi domain open api. 
Admin discord menyarankan untuk meminta txt key nya disini.
Terima kasih.

**Comment by fjtiaratsalsa** [comment]
Halo kak, untuk dns txt key-nya bisa download dokumentasi terbaru disini ya: https://tokoku.itemku.com/open-api

Semoga membantu kak 👍

**Comment by rialdytrike** [comment]
![Screenshot_20](https://github.com/FIVEJACK/itemku-seller-open-api/assets/16575459/ea5f4a32-81b7-4239-9408-24d4ab4f942c)
![Screenshot_21](https://github.com/FIVEJACK/itemku-seller-open-api/assets/16575459/ddb9b690-df00-4f64-bb50-e19b946df6c2)
apakah shopname itu sama dengan slug alamat toko kita ?

**Comment by nandhikawph** [comment]
Hi @rialdytrike , ya benar, shopname disamakan dengan slug alamat toko kamu
Nanti hasilnya akan menjadi "v-api-itemku-toko-rame=1"

**Comment by rialdytrike** [comment]
oke terimakasih

**Comment by fijrid** [comment]
Halo, nanya dong. Saya udah nambahin DNS txt di Cloudflare. Tapi kok ketika saya cek di https://www.nslookup.io/txt-lookup/ tetap gak ada ya
