### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by TuesanddayStudio** [FIVEJACK/itemku-seller-open-api#10]
Kenapa respon dari sandboxnya Unauthorized ya min? Apa ada yang salah sama metode yg kupake ini?

![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/143714194/0003aa8d-2d38-4621-a178-f8bf91f822f4)

**Comment by fjtiaratsalsa** [comment]
halo kak @TuesanddayStudio, boleh dicoba untuk pakai reference code dari sini ya: https://stackoverflow.com/questions/65773502/how-to-generate-jwt-in-php

Untuk header hanya perlu alg HS256 saja seharusnya kak

Semoga membantu ya kak 👍🙏

**Comment by TuesanddayStudio** [comment]
Untuk setting callbacknya gimana kak?

**Comment by fjtiaratsalsa** [comment]
@TuesanddayStudio bisa request lewat kendala itemku di discord ya kak untuk setting callback nya
