### ISSUE TITLE
Perbedaan jumlah key pada response endpoint /order/list

### ISSUE THREAD

**Issue by eldhoral** [FIVEJACK/itemku-seller-open-api#11]
Halo, 
saya menggunakan endpoint /order/list untuk mengecek orderan baru dan orderan selesai. Namun baru kali ini ada perbedaan jumlah key pada response APInya. Saya lampirkan perbedaan responsenya dibawah 

        "success": true,
        {
            "order_id": ,
            "order_number": "",
            "product_id": ,
            "price": ,
            "quantity": ,
            "game_name": "",
            "product_name": "",
            "using_delivery_info": 0,
            "delivery_info_field": null,
            "required_information": "",
            "delivery_info": null,
            "order_income": 
        },
        
        {
            "order_id": ,
            "order_number": "",
            "product_id": ,
            "price": ,
            "quantity": ,
            "game_name": "",
            "product_name": " ",
            "using_delivery_info": 0,
            "delivery_info_field": null,
            "status": "DELIVERED",
            "required_information": "",
            "delivery_info": null,
            "order_income": 
        },
        
2 response diatas dihit menggunakan param "order_status": "REQUIRE_PROCESS". Expectednya key "success" mempunyai value **false** instead of **true** karena key "status" pada response tidak ada yang bervalue "REQUIRE_PROCESS".

Hipotesa saya karena pada response[0] tidak memiliki key "status", maka key "success" mengembalikan value **true** instead of **false**.

Ini expected responsenya jika hipotesa saya benar.

```
{
    "success": false,
    "data": null,
    "message": "We cannot find order with this ID that belongs to you",
    "statusCode": "ORDER_NOT_FOUND"
}
```

Mohon feedbacknya.
Terimakasih

**Comment by LandakX** [comment]
Apakah format parameter ketika hit API nya sudah benar kak ?

**Comment by eldhoral** [comment]
Format param, header, dan auth sudah sesuai semua. Selama ini gak ada masalah, cuma baru ketahuan kemarin ada response aneh seperti itu. Untungnya waktu itu saya sedang matikan auto process order di sistem saya.

**Comment by LandakX** [comment]
Allhamdullilah selama auto process belum kejadian seperti itu kak, sepertinya pihak dev ITEM KU yang harus ikut check, takutnya ada masalah di paramter  key`order_status : "REQUIRE_PROCESS"`

**Comment by eldhoral** [comment]
Iya minta tolong di cek ya **ITEMKU**, takutnya kedepannya akan kejadian lagi response aneh seperti ini. Di sisi saya juga akan dibuat handling tambahan untuk error seperti ini. Kalau butuh curl dan responsenya untuk DEVnya cek, bisa DM saya ya di discord channel lounge open-api. Terimakasih.

**Comment by LandakX** [comment]
Bukan saya pihak dev nya kak, saya coba membatu saja

**Comment by rico-fj** [comment]
halo ka @eldhoral mohon maaf ya sebelumnya..
bisa di coba kembali ka untuk retrieve dengan menggunakan filter oder_status.

makasi ka
