### ISSUE TITLE
Update price mendapatkan response 422

### ISSUE THREAD

**Issue by LandakX** [FIVEJACK/itemku-seller-open-api#12]
Endpoint
https://tokoku-gateway.itemku.com/api/product/price/update

Header param
`"Authorization: Bearer XXXX",
"Content-Type: application/json",
"Content-Length: 38",
"X-Api-Key: XXXXX",
"Nonce: XXXXX",
"alg: HS256"`

Body param
`{
    "product_id": 12345,
    "new_price": 28000
}`

Response param
`{
        "success": false,
        "data": [],
        "message": "Terjadi kesalahan sistem",
        "statusCode": 422
}`

Ini belum tau error kenapa, kalau di dokumentasi https://files.itemku.com/document/Tokoku+API+Docs.pdf 422 tuh error payload, tapi payload saya sudah sesuai, mohon bantuannya pihak developer / programmer item ku

**Comment by fjtiaratsalsa** [comment]
@Xanity16 halo kak apa bisa dicoba kembali?

**Comment by LandakX** [comment]
@fjtiaratsalsa Baik saya coba kembali

**Comment by LandakX** [comment]
@fjtiaratsalsa Ok sudah bisa case close ya kak terima kasih
