### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by nubuntu** [FIVEJACK/itemku-seller-open-api#13]
![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/1622745/0196b870-5437-4c3d-bb2c-c8b83e8fa4f1)

ini code curl nya
```
curl --location 'https://sandbox-api-tokoku.itemku.com/dev/api/order/generate' 
--header 'Authorization: Bearer eyJYLUFwaS1LZXkiOiI3UUF0Rm5sSDkzcjgiLCJOb25jZSI6MTcwNzcyMzI3Njk4MiwiYWxnIjoiSFMyNTYifQ.eyJxdWFudGl0eSI6MSwiZ2FtZV9pZCI6NTEsIml0ZW1fdHlwZV9pZCI6OTV9.sigXsN8vIjfctQk2Zoh8uG-_RpGhTglKVK385bxOxt0' 
--header 'Nonce: 1707723276982' 
--header 'X-Api-Key: XXXXXXXXX' 
--header 'Content-Type: application/json' 
--data '{"quantity":1,"game_id":51,"item_type_id":95}'
```

saya cek di jwt.io signaturenya valid

![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/1622745/49b76136-151f-4679-a56d-ea44d274224f)

ini code yang saya pakai untuk menggenerate signature

[https://playcode.io/1759098](https://playcode.io/1759098)

![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/1622745/58c19eb0-0571-464e-a774-ef3215d08102)

sudah sesuai dengan contoh yang ada di dokumentasi

![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/1622745/6664883b-91fc-45eb-bfd0-091f10d30c99)
 
 tetapi response nya Unauthorized, tolong di cek om salahnya dimana ya? :pray::pray::pray:

**Comment by widi-fj** [comment]
Hello, ini kodenya masih kita proses cek dulu ya kurangnya dimana.

Untuk api key dan secret key baru, nanti dari tim akan dikabari di discord. Mungkin boleh dicoba lagi dengan key baru sambil kita cek kode yang ini.

Mungkin yang ingin aku tanya, timestamp yang digunakan untuk `Nonce` tersebut apakah sudah benar timestamp sekarang? Karena kalau timestampnya terlalu lampau, akan unauthorized

**Comment by nubuntu** [comment]
![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/1622745/d804c97e-09c8-493f-9da4-50e20a264e25)
timestamp nya sudah betul waktu sekarang, pertanyaan length digitnya 13 apa 11? soalnya saya liat di dokumentasi length digit nya 11
![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/1622745/91d40d2d-b7e7-4ef9-a479-3cd705f8e36f)

![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/1622745/f1ee1b63-f36d-49e1-a9af-3bb0d01f637f)

tapi saya coba keduanya length 13 dan 11 juga sama aja Unauthorized

**Comment by nubuntu** [comment]
Apa harus mendaftarkan IP Address saya dulu?

**Comment by nubuntu** [comment]
![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/1622745/70815e1f-94ce-4243-bda4-866ab10494b0)
Saya test pakai credential production juga sama hasilnya unauthorized , salah dimananya ini? :dizzy_face::dizzy_face:

**Comment by widi-fj** [comment]
Boleh coba ini apakah bisa? Ini aku coba time nya dibagi 1000

```
const crypto = require('crypto');
const axios = require('axios');

class Utils {
  static base64Encode(str) {
    return Buffer.from(str)
      .toString('base64')
      .replace(/\+/g, '-')
      .replace(/\//g, '_')
      .replace(/=+$/, '');
  }

  static hmacSHA256(key, data) {
    return this.base64Encode(
      crypto.createHmac('sha256', key).update(data).digest()
    );
  }

  static generateSignature(headers, data, key) {
    const base64Headers = this.base64Encode(JSON.stringify(headers));
    const base64Data = this.base64Encode(JSON.stringify(data)); 
    const unsigned = `${base64Headers}.${base64Data}`;
    const signatureSha = this.hmacSHA256(key, unsigned);
    return `${unsigned}.${signatureSha}`;
  }
}

const apiKey = 'api_key';
const secretKey = 'secret_key';
const now = Date.now() / 1000;
const body = {
    "date_start": "2024-02-10"
};
const signExample = Utils.generateSignature(
  {
    'X-Api-Key': apiKey,
    Nonce: now,
    alg: 'HS256',
  },
  body,
  secretKey
);

axios.post('https://sandbox-api-tokoku.itemku.com/api/order/list', body, {
        method: 'POST',
        headers: {
            'Authorization': 'Bearer ' + signExample,
            'Content-Type': 'application/json',
            'X-Api-Key': apiKey,
            'Nonce': now
        }
    })
        .then(response => console.log(response.data))
        .catch(err => console.error(err));
```

**Comment by nubuntu** [comment]
oalah ternyata pakai timestamp 10 digit, sudah bisa min, terima kasih. itu di dokumentasi 11 digit soalnya, mudah2an dikoreksi biar ga bikin bingung
![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/1622745/4578b4e1-6169-4335-9f3e-727873579994)
