### ISSUE TITLE
[Request Feature] Komplain & Chat Pembeli Webhook

### ISSUE THREAD

**Issue by apapedulimu** [FIVEJACK/itemku-seller-open-api#14]
Halo, 

Permisi, izin request feature, karena sekarang sudah ada fitur baru di Itemku, yaitu "Discord Webhook" untuk Kendala Pesanan, Pesanan Baru, dan Chat pembeli. Apakah sekiranya bisa juga mengimplementasikan fitur tersebut ke Open API untuk mengirim notifikasi terkait ke preferable channel yang seller mau? 

Terimakasih.

**Comment by azisssani** [comment]
Halo @apapedulimu 

Untuk membedakan target channel utk tiap jenis notifikasi tokoku, kakak bisa mengatur melalui menu integration channel discord

Di bagian **Channel** bisa dropdown untuk pilih channel yang diinginkan
![Screenshot 2024-02-27 155312](https://github.com/FIVEJACK/itemku-seller-open-api/assets/91949833/5a1dafd9-213f-43ba-8c5f-dba899c997bb)


Kira2 menjawab ga ya dengan problem yang kakak alami?

**Comment by apapedulimu** [comment]
Halo Kak @azisssani , 

Maksud saya ketika ada kendala pesanan / chat pembeli, di kirim lewat open api seperti itemku mengirimkan webhook pesanan baru.  Apakah hal tersebut memungkinkan ya kak?

Apakah jelas ya pertanyaan saya kak? 

Terimakaish.

**Comment by azisssani** [comment]
Oh oke jelas kak
Intinya ingin supaya selain bisa terima notifikasi order lewat API, kakaknya juga ingin bisa nerima notif kalo ada Kendala Pesanan atau Chat lewat API. 

Untuk saat ini, kami tampung dulu ya mas sebagai masukan. 

Terima kasih

**Comment by apapedulimu** [comment]
Siap Kak, Terimakasih Banyak. Izin saya close
