### ISSUE TITLE
Sistem api tidak terbaca

### ISSUE THREAD

**Issue by Lintarjsr** [FIVEJACK/itemku-seller-open-api#15]
Halo kak.. ini ada masalah setiap orderan diamond ML yg ID & Server ada spasi tidak terbaca oleh API
![IMG_4961](https://github.com/FIVEJACK/itemku-seller-open-api/assets/161554488/2534a888-e508-4344-b531-9269a8833328)

**Comment by nandhikawph** [comment]
Hi [Lintarjsr](https://github.com/Lintarjsr), bisa dibantu share url api yang ditembak?
Dan contoh requestnya beserta response error yang didapat?
