### ISSUE TITLE
Tidak bisaa terkoneksi

### ISSUE THREAD

**Issue by ERZY404** [FIVEJACK/itemku-seller-open-api#16]
Bisa minta tolong kenapa tidak bisa ya ? saya coba menggunakan localhost pun menjadi unauthorized 

![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/106662849/68ef11b8-086d-42bb-a6a7-cec3d719d54a)

**Comment by fjtiaratsalsa** [comment]
halo kak @ERZY404, untuk request method nya sesuai dokumentasi pakai POST
