### ISSUE TITLE
Produk Pulsa

### ISSUE THREAD

**Issue by indra2607** [FIVEJACK/itemku-seller-open-api#17]
Halo kak, produk pulsa untuk pengiriman instan setiap ada orderan masuk tiba tiba terbatal otomatis dan alasan pembatalan tertulis "pembeli salah memasukan user id atau informasi yang di butuhkan bagi penjual"

**Comment by fjtiaratsalsa** [comment]
Halo kak, bisa help share order numbernya untuk kami cek? Terima kasih

**Comment by indra2607** [comment]
Ini kak OD000000125515088

**Comment by fjtiaratsalsa** [comment]
Halo kak untuk response dari API callback milik seller untuk nomor pesanan OD000000125515088 ini mendapat error 
"{\"status\":false}"

mohon cek dari sistem API milik seller apakah request tersebut membuat sebuah request ke api /order/action di itemku untuk reject order dengan no. pesanan OD000000125515088

**Comment by indra2607** [comment]
oke baik kak, untuk orderan top up game lain via id yang orderannya tiba tiba terbatal otomatis juga sama?

**Comment by fjtiaratsalsa** [comment]
iya betul kak, untuk detail log bisa request via discord juga dan mencantumkan nomor pesanan kak 👍

**Comment by indra2607** [comment]
halo kak, ada contoh payload kategori buat pulsa ga?

**Comment by fjtiaratsalsa** [comment]
Halo kak @indra2607 ini terkait field required_information ya?

Untuk pulsa saat ini ada 2 macam format required_information: 

Format 1:
`{"required_information":"08XXXX"}`

Format 2:
Langsung value "08XXXX"
