### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by ERZY404** [FIVEJACK/itemku-seller-open-api#18]
Tolong bagaimana ini cara mengatasinya , saya sudah menggunakan api key testing sama aja

![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/106662849/c4288598-1724-4e84-a5f8-549fb688fd53)

**Comment by nandhikawph** [comment]
Apakah hasil hashnya sama dengan hasil signature hash di jwt.io?

**Comment by ERZY404** [comment]
![IMG_20240424_170616_401](https://github.com/FIVEJACK/itemku-seller-open-api/assets/106662849/3e44710a-742f-4165-87b7-21ba44ead870)

![IMG_20240424_170619_428](https://github.com/FIVEJACK/itemku-seller-open-api/assets/106662849/a8f9b074-1378-4330-a6b3-8094908e20dc)


Saya sudah meng hashnya dan masalahnya tetap sama :))

**Comment by ERZY404** [comment]
![IMG_20240424_170621_394](https://github.com/FIVEJACK/itemku-seller-open-api/assets/106662849/d6d1df83-f002-4243-83ea-0f1b0d881d4b)
![IMG_20240424_170826_881](https://github.com/FIVEJACK/itemku-seller-open-api/assets/106662849/0b1e7f82-3520-4a89-9ea3-e84185350921)
