### ISSUE TITLE
hit gagal ke website

### ISSUE THREAD

**Issue by hendy046** [FIVEJACK/itemku-seller-open-api#19]
OD000000127861995
tolong cek order id ini kak kenapa gak ke hit ke web

**Comment by fjtiaratsalsa** [comment]
Halo kak @hendy046 
untuk OD000000127861995 saat kirim callback ke API 

Dari log kami mendapat response:

`"<!-- DEBUG-VIEW START 4 APPPATH/Views/Home/index.php -->\n<!-- DEBUG-VIEW START 3 APPPATH/Views/template.php -->\n<!DOCTYPE html>\r\n<html lang=\"en\">\r\n    \r\n    <!-- DEBUG-VIEW START 1 APPPATH/Views/head.php -->\n    <head>\n<script type=\"text/javascript\"  id=\"debugbar_loader\" data-time=\"1713945163.082940\" src=\"https://excellentstore.id/index.php?debugbar\"></script><script type=\"text/javascript\"  id=\"debugbar_dynamic_script\"></script><style type=\"text/css\"  id=\"debugbar_dynamic_style\"></style><script class=\"kint-rich-script\">void 0===window.kintShared&&(window.kintShared=function(){\"use strict\";var e={dedupe:function(e,n){return[].forEach.call(document.querySelectorAll(e),function(e){e!==(n=!n||!n.ownerDocument.contains(n)?e:n)&&e.parentNode.removeChild(e)}),n},runOnce:function(e){\"complete\"===document.readyState?e():window.addEventListener(\"load\",e)}};return window.addEventListener(\"click\",function(e){var n;e.target.classList.contains(\"kint-ide-link\")&&((n=new XMLHttpRequest).open(\"GET\",e.target.href),n.send(null),e.preventDefault())}),e}());\nvoid 0===window.kintRich&&(window.kintRich=function(){\"use strict\";var l={selectText:function(e){var t=window.getSelection(),a=document.createRange();a.selectNodeContents(e),t.removeAllRanges(),t.addRange(a)},each:function(e,t){Array.prototype.slice.call(document.querySelectorAll(e),0).forEach(t)},hasClass:function(e,t){return!!e.classList&&e.classList.contains(t=void 0===t?\"kint-show\":t)},addClass:function(e,t){e.classList.add(t=void 0===t?\"kint-show\":t)},removeClass:function(e,t){return e.classList.remove(t=void 0===t?\"kint-show\":t),e},toggle:function(e,t){var a=l.getChildren(e);a&&((t=void 0===t?l.hasClass(e):t)?l.removeClass(e):l.addClass(e),1===a.childNodes.length&&......`

Apa ada permasalahan dalam sistem API excellent store tsb kak?

**Comment by hendy046** [comment]
Itu hit method post or get???

**Comment by hendy046** [comment]
kak ini masih gak bisa ke hit dengan order id OD000000127884380

**Comment by fjtiaratsalsa** [comment]
Halo ka @hendy046, untuk HIT API Callback seller kita selalu hit method POST sesuai di Dokumentasi.

Untuk OD000000127884380 response nya juga sama seperti OD000000127861995 dari log kami ketika HIT ada error seperti sebelumnya.

**Comment by hendy046** [comment]
kembali kak tolong cek log
OD000000128113682
karena kemarin sudah di rubah tapi orderan tetap belum masuk ke api web kami

**Comment by hendy046** [comment]
tolong di bantu kak

**Comment by fjtiaratsalsa** [comment]
Log untuk: OD000000128113682

```
Error: Client error: `POST [host & path warungdm]` resulted in a `405 Method Not Allowed` response:
 <!DOCTYPE html>
 <html>
 <head>
     <meta charset="UTF-8" />
     <meta name="robots" content="noindex,nofollow,noarchive"  (truncated...)
```

**Comment by hendy046** [comment]
kenapa orderan OD000000136511108 gak ke hit ke web saya kak??? pagi tadi aman aja..
