### ISSUE TITLE
cara testing

### ISSUE THREAD

**Issue by hendy046** [FIVEJACK/itemku-seller-open-api#2]
aku sudah mendapat api key dan scretkey dari itemku dan sudah di pasang di web aku oleh dev, lalu di beri testing api key, lalu bagaimana selanjutnya untuk callback dan testing pembelian agak terkoneksi

**Comment by fjtiaratsalsa** [comment]
Halo kak untuk permintaan callback Order API bisa melalui discord Lapak Juragan ya

Untuk melakukan testing pembelian bisa melalui sandbox API menggunakan key testing, mengacu di dokumentasi terbaru ya

**Comment by hendy046** [comment]
aku sudah selesai callback antra web dan itmku, lalu apakh ini sudah bisa otomatis ?

**Comment by fjtiaratsalsa** [comment]
Halo kak, untuk callback bisa dikonfirmasi lewat discord ya untuk status setup-nya, jika sudah, maka akan otomatis terkirim ketika ada pembeli yang membayar.

**Comment by hendy046** [comment]
tadi ada orderan kak tapi API nya gak jalan bisa diinfo kak errornya dimna? sehingga aku harus memproses manual kak
![Uploading Screenshot_2023-12-19-09-28-50-719_com.android.chrome.jpg…]()

**Comment by hendy046** [comment]
![Screenshot_2023-12-19-09-28-50-719_com android chrome](https://github.com/FIVEJACK/itemku-seller-open-api/assets/152580554/6a9cd1e4-ab24-49af-af65-d4cc7155ab65)

**Comment by nandhikawph** [comment]
Halo Hendy, untuk proses API-nya apa bisa dibantu detail endpoint api yang bermasalah?

**Comment by hendy046** [comment]
dari log server gak ada hit dari itemku, dimna ya kak salhnya?

**Comment by hendy046** [comment]
kenapa kak gak ada log di server aku callbacknya

**Comment by fjtiaratsalsa** [comment]
Halo kak terkait callback log hit dari itemku ke API seller, kakak bisa request log lewat discord dengan mencantumkan nomor pesanan ya. Saya izin tutup issues ini karna testing nya sudah aman ya kak

Jika nanti masih menemukan issue terkait callback, kakak bisa buat issue baru ya

Terima kasih
