### ISSUE TITLE
URL ENDPOINT SANDBOX ORDER/ACTION

### ISSUE THREAD

**Issue by ERZY404** [FIVEJACK/itemku-seller-open-api#20]
Halo untuk test sandbox di dokumentasi hanya ada generate order, generate product, dan list. Untuk action atau deliver produknya bagaimana ya ?

**Comment by ERZY404** [comment]
![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/106662849/993d8351-f99e-4d2a-b326-5a7ca2a5b3be)
apakah yang ini ? jika iya bagaimana cara merubah statusnya atau endpointnya apa

**Comment by fjtiaratsalsa** [comment]
Untuk action ada di section Order Action ka @ERZY404 
![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/27803046/a2209bcd-d9ad-41d1-b7a5-4b49b99fc8cc)

**Comment by fjtiaratsalsa** [comment]
Halo ka @ERZY404 untuk Action di Sandbox kita memakai Dokumentasi yang sama dengan Production, hanya saja host nya nanti bisa diganti dengan yang sandbox https://sandbox-api-tokoku.itemku.com/

![image](https://github.com/FIVEJACK/itemku-seller-open-api/assets/27803046/1a3823c1-bd54-435f-828c-3b661b470a1b)

Semoga membantu kak

**Comment by ERZY404** [comment]
Jadi untuk action url nya tidak ada /dev bagian sandbox nya ya kak?

**Comment by ERZY404** [comment]
Contoh : generate order ( https://sandbox-api-tokoku.itemku.com/dev/api/order/generate )

Sedangkan action ( https://sandbox-api-tokoku.itemku.com/api/order/action?

**Comment by fjtiaratsalsa** [comment]
iyes betul ka @ERZY404
