### ISSUE TITLE
"Required Information" Pada Produk Global - Mobile Legends MY

### ISSUE THREAD

**Issue by apapedulimu** [FIVEJACK/itemku-seller-open-api#21]
Halo, 

Saya kebetulan berjualan produk global, salah satunya Mobile Legends MY, saya mendapati required information yang berbeda dengan produk lokal / indonesia, berikut ini perbedaannya: 

```
Mobile Legends MY : {"User ID":"1580771062","Zone ID":"16670"}
Mobile Legends ID : {"player_id":"97859206","zone_id":"2507"} 
```

Apakah ini permanen bahwa jika selain mobile legends indo menggunakan "User ID" ,"Zone ID daripada "player_id" dan"zone_id" ? 

Terimakasih.

**Comment by fjtiaratsalsa** [comment]
Halo kak @apapedulimu untuk mobile legends MY sudah kami perbaiki. Terima kasih untuk informasinya 🙏
