### ISSUE TITLE
Game yang ada list server

### ISSUE THREAD

**Issue by fickycj08** [FIVEJACK/itemku-seller-open-api#22]
halo mau tannya, untuk game yang ada list server seperti genshin dll apakah harus tetap harus manual? karena di temku engga ada format bakunya sehingga buyer bisa isi asal

**Comment by fjtiaratsalsa** [comment]
Halo kak @fickycj08 untuk saat ini server untuk Genshin dari buyer masih bisa input manual, namun kedepannya akan kami pertimbangkan untuk mengimplementasikan sistem otomatisasi yang lebih efisien. Terima kasih atas masukannya.

**Comment by apapedulimu** [comment]
Halo kak @fjtiaratsalsa, saran saya untuk genshin servernya dibuat list dropdown saja kak, karena mengingat produk genshin menjadi produk internasional dan ada perbedaan penulisan seperti "euro / europe  / eropa" juga untuk mengurangi typo, karena beberapa hari yang lalu  banyak yang typo "Asia menjadi Aisa" dsb.
