### ISSUE TITLE
Issue Penambahan Staff

### ISSUE THREAD

**Issue by LandakX** [FIVEJACK/itemku-seller-open-api#25]
<img width="752" alt="Tangkapan Layar 2024-07-10 pukul 21 56 40" src="https://github.com/FIVEJACK/itemku-seller-open-api/assets/28718647/d331f124-3cbe-4758-9f93-b1ed41aa706c">

Email staff tidak bisa di input seperti contoh **admin@email-store.com** karena domain toko saya seperti ini **toko-saya.com**

**Comment by fjtiaratsalsa** [comment]
Halo kak @Xanity16 bisa dicoba memakai email gmail terlebih dahulu ya kak
Apakah dari kak @Xanity16 ada kebutuhan untuk memakai email non Gmail untuk staff?

**Comment by LandakX** [comment]
@fjtiaratsalsa Yap betul saya membutuhkan email non gmail

**Comment by fjtiaratsalsa** [comment]
Ok kak @Xanity16 terima kasih untuk sarannya, dari tim akan pertimbangkan untuk pengembangan produk ke depan. Untuk sementara bisa pakai email dengan domain gmail terlebih dahulu ya :)
