### ISSUE TITLE
Error get data order

### ISSUE THREAD

**Issue by LandakX** [FIVEJACK/itemku-seller-open-api#26]
Response JSON ITEMKU Could not resolve host: tokoku-gateway.itemku.com | 6 | {"url":"https:\/\/tokoku-gateway.itemku.com\/api\/order\/list","content_type":null,"http_code":0,"header_size":0,"request_size":0,"filetime":-1,"ssl_verify_result":0,"redirect_count":0,"total_time":0.000142,"namelookup_time":0,"connect_time":0,"pretransfer_time":0,"size_upload":0,"size_download":0,"speed_download":0,"speed_upload":0,"download_content_length":-1,"upload_content_length":-1,"starttransfer_time":0,"redirect_time":0,"redirect_url":"","primary_ip":"","certinfo":[],"primary_port":0,"local_ip":"","local_port":0,"http_version":0,"protocol":0,"ssl_verifyresult":0,"scheme":"","appconnect_time_us":0,"connect_time_us":0,"namelookup_time_us":0,"pretransfer_time_us":0,"redirect_time_us":0,"starttransfer_time_us":0,"total_time_us":142}

**Comment by fjtiaratsalsa** [comment]
@Xanity16 Halo kak, apakah boleh dicoba test beberapa opsi berikut:

- coba hit url tersebut dengan browser (apakah berhasil dengan tulisan "method not allowed")
- menggunakan cli ubuntu dengan command `dig https://tokoku-gateway.itemku.com` , dan share hasil IP dari answer section nya?

**Comment by LandakX** [comment]
Sudah bisa lagi waktu itu jam 09:00 WIB, sebelumnya saya hit gaada ini coba hit url tersebut dengan browser (apakah berhasil dengan tulisan "method not allowed")
