### ISSUE TITLE
Tidak menerima callback pesanan

### ISSUE THREAD

**Issue by indra2607** [FIVEJACK/itemku-seller-open-api#27]
Saya dapet beberapa orderan dari sore tapi tidak menerima callback nya kak

**Comment by fjtiaratsalsa** [comment]
Halo kak @indra2607 boleh share nomor pesanannya untuk kami cek?

**Comment by indra2607** [comment]
OD000000131140897
OD000000131140988
OD000000131141350
OD000000131141503
OD000000131141878
OD000000131142570
OD000000131142627

**Comment by fjtiaratsalsa** [comment]
Halo kak @indra2607 untuk callback pesanan tersebut dalam log kami mendapatkan response 

Error: cURL error 28: Operation timed out after 5002 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for [callback url seller]
