### ISSUE TITLE
Inkonsistensi value required_information

### ISSUE THREAD

**Issue by gradyyo** [FIVEJACK/itemku-seller-open-api#28]
Hi, saya perhatikan kenapa ada inkonsistensi value untuk field required_information ya? Padahal ini di produk dan denom yang sama.

Tantan - 60 Coins
OD000000131513395 -> "required_information": "xxx",
OD000000131521816 -> "required_information": "{\"Tantan ID\":\"xxx\"}",
OD000000131569752 -> "required_information": "{\"required_information\":xxx}",

Telkomsel - Pulsa 3000
OD000000131373524 -> "required_information": "xxx",
OD000000131473485 -> "required_information": "{\"Nomor Handphone \":\"xxx\"}",

Apakah expected behaviour value dari API nya inkonsisten begini?

**Comment by fjtiaratsalsa** [comment]
Halo kak @gradyyo terima kasih untuk reportnya

Untuk format field required_information sementara ini ada 2 format diantaranya 
- "required_information" : "xxx"
- "required_information" : "{"required_information":xxx}"

untuk format selain kedua tersebut masih dalam investigasi tim, mohon menunggu ya kak

**Comment by gradyyo** [comment]
Oke berkabar aja yaa @fjtiaratsalsa

Kalau boleh saran, untuk produk yang cuma butuh single simple data seperti nomor HP / ID, sepertinya lebih stabil pakai `"required_information" : "xxx"`

Karena ada bug juga di UI list riwayat pesanan kalau pakai. Bisa refer ke screenshot di bawah ya
`"required_information": "{"required_information":xxx}".`
![image](https://github.com/user-attachments/assets/4dda664c-647c-46e8-ab83-bbcafc1bb45b)
`"required_information" : "xxx"`
![image](https://github.com/user-attachments/assets/55e0df4e-7945-49e7-9b11-17996df90b92)

**Comment by fjtiaratsalsa** [comment]
Wah, thanks banget kak @gradyyo udah report terkait bug tersebut. Kami cek terlebih dahulu ya

**Comment by LandakX** [comment]
@gradyyo Iya kak memang begitu formatnya, makannya saya suka check 2 kali hehe

**Comment by gradyyo** [comment]
@Xanity16 Iya sekarang memang begitu formatnya, tapi aneh banget kalau nggak konsisten meskipun satu produk dan satu denom yang sama. API kontraknya jadi nggak valid. Makanya saya menyarankan biar dibuat selalu konsisten

**Comment by LandakX** [comment]
@gradyyo Sekarang produk aku paling yang ada di dokumentasi API aja kak

**Comment by fjtiaratsalsa** [comment]
Halo kak @gradyyo, untuk perihal format required info pada pesanan: 

OD000000131521816 -> "required_information": "{"Tantan ID":"xxx"}"

Dari tim sudah fix untuk kesalahan format tersebut. Apakah dari kakak masih menerima dengan kesalahan format tersebut?

Untuk perihal inconsistent untuk required_information sudah kami tambahkan format detail-nya di docs. Semoga membantu ya kak :)
![image](https://github.com/user-attachments/assets/3d8d2e7d-6096-403c-b857-1f3f310d70c6)
