### ISSUE TITLE
DNS TXT FOR ITEMKU

### ISSUE THREAD

**Issue by fijrid** [FIVEJACK/itemku-seller-open-api#3]
Halo, nanya dong. Saya udah nambahin DNS txt di Cloudflare. Tapi kok ketika saya cek di https://www.nslookup.io/txt-lookup/ tetap gak ada ya

**Comment by fjtiaratsalsa** [comment]
Halo kak @fijrid, apakah pengaturan Cloudflare tersebut sudah sesuai dengan dokumentasinya?
https://www.cloudflare.com/learning/dns/dns-records/dns-txt-record/
