### ISSUE TITLE
ERROR JSON dan REQUIRED_INFORMATION

### ISSUE THREAD

**Issue by maravilleeee** [FIVEJACK/itemku-seller-open-api#30]
Halo, ini untuk kategori STREAMING (Papaya Live dan LivuChat) kenapa datanya selalu labil yang masuk?
Karena setiap ada orderan Papaya Live dan Livuchat yang masuk di web kami, langsung menyebabkan web kami 500 | SERVER ERROR. Membuat admin panel tidak bisa terbuka (untuk riwayat pesanan).

![image](https://github.com/user-attachments/assets/35aa5d96-fcdb-4d4e-ab6c-a3a351764d11)

Di harap untuk tim itemku fix segera error dari json dan required_information karena data yang masuk selalu ga sesuai dan berubah2. Tolong balasannya sesegera mungkin. Karena sangat merepotkan untuk reset data setiap saat papaya live dan livuchat masuk orderan ke web. Thankyou

**Comment by fjtiaratsalsa** [comment]
Halo kak @maravilleeee mohon maaf untuk ketidaknyamanannya ya, untuk saat ini format required_information dengan value required_information memiliki 2 format, untuk sementara dari kakak bisa handle format required information seperti di docs ya kak 🙏
![image](https://github.com/user-attachments/assets/5b3a87ab-a8c7-4f7c-8889-0d01f414e050)

Saat ini dari tim masih proses investigasi dan reformatting required information tersebut, mohon kesediaannya menunggu ya kak

**Comment by fjtiaratsalsa** [comment]
Halo kak @maravilleeee apakah issue-nya masih occur saat ini? 
Dari tim sudah melakukan perbaikan dengan pengubahan Format 2 (Legacy) ke Format 1
