### ISSUE TITLE
API ITEMKU

### ISSUE THREAD

**Issue by hayatogetdown** [FIVEJACK/itemku-seller-open-api#32]
Halo semuanya saya ingin bertanya terkait cara menggunakan/mengintegrasikan API di Tokoku Itemku..
mohon bantuannya

**Comment by fjtiaratsalsa** [comment]
Halo kak @haryanto2110 

Untuk memudahkan proses integrasi, kami telah menyediakan dokumentasi lengkap yang bisa kak @haryanto2110 ikuti langkah demi langkah. Untuk dokumentasinya bisa dicek di sini: https://files.itemku.com/document/Tokoku+API+Docs.pdf

Dari dokumentasi tersebut, kak @haryanto2110 akan menemukan semua informasi yang diperlukan untuk mengintegrasikan API dengan lancar.

Jika nanti ada hal-hal yang kurang jelas atau butuh bantuan lebih lanjut setelah membaca dokumentasi, jangan ragu untuk bertanya kembali ya. Kami siap membantu, kak!

Selamat mencoba! 😊

**Comment by hayatogetdown** [comment]
apa ada team yang bisa membantu untuk integrasi kak?
