### ISSUE TITLE
[Webhook] Inconsistent required_information for sausageman game

### ISSUE THREAD

**Issue by arisawali2014** [FIVEJACK/itemku-seller-open-api#33]
Webhook dari game sausageman itu id sama nickname tersambung dalam 1 value contoh webhook yang saya dapat:

```json
{
   "order_id":"xxxxxx",
   "order_number":"xxxxxxxx",
   "product_id":"xxxxx",
   "price":"xxxx",
   "quantity":1,
   "order_income":"xxxx",
   "is_from_ads":false,
   "ads_fee":0,
   "game_name":"Sausage Man",
   "product_name":"718 Candies",
   "status":"REQUIRE_PROCESS",
   "required_information":"{\"required_information\":\"9zta8r , CPL•|Rinn\"}",
   "using_delivery_info":false,
   "delivery_info_fields":null,
   "delivery_info":null
}
```
mohon untuk diperbaiki.  tolong dipisahkan menjadi 2 key value. nickname dan ID

**Comment by fjtiaratsalsa** [comment]
Halo kak @arisawali2014 

Mohon maaf untuk issue yang didapat ya kak. Saat ini tim kami sedang menginvestigasi permasalahan tersebut, mohon menunggu ya kak. Terima kasih

**Comment by fjtiaratsalsa** [comment]
Halo kak @arisawali2014 untuk issue ini sedang dalam proses ya kak, mohon menunggu pengumuman selanjutnya untuk format terbaru nanti ya kak. Terima kasih
