### ISSUE TITLE
MENGIRIM PESANAN BISA TANPA DATA

### ISSUE THREAD

**Issue by ERZY404** [FIVEJACK/itemku-seller-open-api#34]
$response = $itemku->update(133609053, 'DELIVER', [
        'delivery_info' => [],
    ]);
    
    
![image](https://github.com/user-attachments/assets/fbe297c0-be49-4904-bf81-cda6c8e9a852)

bisakah tambahkan validasi ? karena jika seperti ini saya tidak tau bagaimana jika gagal dalam pengiriman pesanannya

**Comment by fjtiaratsalsa** [comment]
Halo kak @ERZY404, terima kasih untuk laporannya. Kami akan coba investigasi issuenya terlebih dahulu ya, mohon menunggu

**Comment by ERZY404** [comment]
baik ditunggu kak

**Comment by fjtiaratsalsa** [comment]
Halo kak @ERZY404 untuk validasi ini akan applied di Rabu, 6 November 2024 pukul 15:00 ya kak
Jika ada issue bisa komen di github ini kembali ya, kak terima kasih untuk feedbacknya :)
