### ISSUE TITLE
Rubah property delivery_info_fields 

### ISSUE THREAD

**Issue by ERZY404** [FIVEJACK/itemku-seller-open-api#36]
![image](https://github.com/user-attachments/assets/d2e1967f-e7ce-470e-aae6-3dff74a34b5b)
Bisa tolong rubah untuk property ini dari null menjadi array ? agar supaya bisa melakukan pengecekan terhadap data yang dikirim

**Comment by fjtiaratsalsa** [comment]
Halo kak @ERZY404 terkait delivery_info_fields bisa refer ke dokumentasi section Delivery Info disini ya https://files.itemku.com/document/Tokoku+API+Docs.pdf

Jika ada kebutuhan use case lebih lanjut boleh kabari ke kami ya kak, terima kasih

**Comment by ERZY404** [comment]
> Halo kak @ERZY404 terkait delivery_info_fields bisa refer ke dokumentasi section Delivery Info disini ya https://files.itemku.com/document/Tokoku+API+Docs.pdf
> 
> Jika ada kebutuhan use case lebih lanjut boleh kabari ke kami ya kak, terima kasih

sudah minta akses ya kak, mohon setujui terimakasih

**Comment by fjtiaratsalsa** [comment]
@ERZY404 halo kak, mohon maaf link nya pakai yang terbaru ya kak, dokumentasi nya ada di page tokoku open api di dashboard seller juga, terima kasih
![image](https://github.com/user-attachments/assets/31d58ffe-8d8d-483e-9ade-33d8eef74ffa)

**Comment by ERZY404** [comment]
halo kak, mohon maaf ini yang di ganti itu apanya ya kak? apakah yg diupdate ini payload ketika callback dikirim?

**Comment by fjtiaratsalsa** [comment]
@ERZY404 boleh share kak kebutuhan kakaknya ini minta untuk mengubah delivery_info_fields menjadi array atau gimana kak?

Jadi dari payload callback yang kami kirim, untuk pemakaian delivery info fields ini bisa merujuk ke dalam condition yang dijabarkan dalam dokumentasi itu kak, untuk bagaimana cara pengiriman payload delivery_info ketika dari kakak hit ke /order/action nanti (deliver order)

**Comment by ERZY404** [comment]
kondisi payload product capcut waktu dikirim itu null sementara di get itu dia array. Artinya valuenya tidak konsisten

product yang pengisiannya EMAIL dan Password

jadi casenya saya mau dibuat konsisten kak
![image](https://github.com/user-attachments/assets/3bc67621-470b-4a34-871e-12653a0c776b)

**Comment by fjtiaratsalsa** [comment]
oh baik kak @ERZY404 terima kasih untuk konfirmasinya, kami cek terlebih dahulu ya kak

**Comment by dakasakti** [comment]
Izin menambahkan. Waktu callback diterima itu productnya memiliki case3. tetapi property `delivery_info_fields` = null.

Tetapi jika di hit dari getList dia sudah benar `delivery_info_fields` = [].

**Comment by fjtiaratsalsa** [comment]
Thanks kak @dakasakti, kami proses cek ya kak terkait itu 👍

**Comment by fjtiaratsalsa** [comment]
Halo kak @ERZY404 dan @dakasakti 

Untuk perubahan ini, kita akan mengikuti dokumentasi ya, dengan menggunakan kondisi:
![image](https://github.com/user-attachments/assets/9698db1d-79ee-4ece-8df3-eb1afd2807a2)

Jadi ada 3 kondisi untuk handle delivery info fields ini:
1. 
**using_delivery_info 0/false
delivery_info_field null**
Order tidak membutuhkan delivery_info payload ketika deliver order melalui api/order/action endpoints
Contoh: ada di kategori Topup

2.
**using_delivery_info 1/true
delivery_info_field null**
Order membutuhkan delivery_info dengan format array dengan length sesuai quantity order, contohnya; ["DELIVERY_INFO_1","DELIVERY_INFO_2"]
Contoh: ada di kategori Voucher

3.
**using_delivery_info 1/true
delivery_info_field Array(should not an empty array)**
Order membutuhkan delivery_info dengan format sesuai yang ada di dalam payload delivery_info_field dengan length sesuai quantity order, contohnya; [{"email":"123@email.com","password":"X12345"}]
Contoh: ada di kategori akun streaming (netflix)

Untuk implementasi ini akan applied di Rabu, 6 November 2024 pukul 15:00

Jika ada pertanyaan terkait ini bisa komen di github ini kembali ya kak, Terima kasih!
