### ISSUE TITLE
Request Parameter Requaire Username

### ISSUE THREAD

**Issue by anmunara** [FIVEJACK/itemku-seller-open-api#37]
Game Pet Simulator 99!
List Item : 
- Gems
- Pet
- Misc
- Potion 
- Enchant
- Ultimate
- HoverBoard

**Comment by fjtiaratsalsa** [comment]
Halo kak @SummerFHD, terima kasih untuk infonya ya! Request ini sedang diproses oleh tim. Untuk kedepannya, agar komunikasi lebih cepat dan interaktif, kamu bisa langsung sampaikan request di server Discord seller dan tim kami bisa merespon lebih cepat. 💬
