### ISSUE TITLE
Timeout Calling API

### ISSUE THREAD

**Issue by arisawali2014** [FIVEJACK/itemku-seller-open-api#38]
bbrapa hari ini sering kali terjadi timout saat call API deliver atau get transaction

timestamp: November 3rd 2024, 12:20:11 AM (39m ago)
<img width="593" alt="image" src="https://github.com/user-attachments/assets/0b927909-639e-44ba-b9ca-cafb614d4668">

jdinya orderan tidak terambil lalu otomatis tercancel. apakah bisa di perbaiki di sisi itemku nya?
Terima kasih.

**Comment by fjtiaratsalsa** [comment]
Halo kak @arisawali2014 sebelumnya mohon maaf untuk ketidaknyamanannya ya kak, apakah dari kakak sudah coba implement retry ketika terjadi timeout untuk hit /order/action?
