### ISSUE TITLE
Callback URL

### ISSUE THREAD

**Issue by refaldy04** [FIVEJACK/itemku-seller-open-api#40]
apakah ada skema callback akan dikirim ulang?
karena misal jika dikita error, jika callbacknya hanya sekali maka order tidak bisa di proses lebih lanjut

**Comment by fjtiaratsalsa** [comment]
Halo kak @refaldy04, terima kasih untuk feedbacknya. Saat ini sistem belum mengimplementasikan proses retry. Namun, kami sudah menyadari pentingnya fitur ini dan saat ini sedang dalam tahap perencanaan dan pengembangan ya kak. Mohon menunggu, terima kasih 😊
