### ISSUE TITLE
cara tahu dns txt

### ISSUE THREAD

**Issue by axiecomunistream2** [FIVEJACK/itemku-seller-open-api#5]
bisa dikirim dokumentasi agar saya tahun dns txt apa yang harus saya isi di dns domain saya.

**Comment by axiecomunistream2** [comment]
saya sudah develop web saya agar bisa menerima api dari itemku dan saya text. ketika di lapor ke itemku,memberi tahu belum ada dns txt nya,padahal di dokumentasi yang saya terima tidak ada tentang dns txt nya

**Comment by fjtiaratsalsa** [comment]
Refer from here: https://github.com/FIVEJACK/itemku-seller-open-api/issues/1

Halo kak, untuk dns txt key-nya bisa download dokumentasi terbaru disini ya: https://tokoku.itemku.com/open-api

Semoga membantu kak 👍
