### ISSUE TITLE
Request Feature Ads Info

### ISSUE THREAD

**Issue by rialdytrike** [FIVEJACK/itemku-seller-open-api#6]
Halo admin saya mau request fitur untuk menambahkan pada data json yg dikirim pada callback. Untuk mengetahui apakah orderan menggunakan iklan atau tidak dan berapa jumlah saldo iklan yg dihabiskan untuk orderan tersebut. Terima kasih,

**Comment by fjtiaratsalsa** [comment]
Halo kak, terima kasih untuk feedback nya kak. Kami akan pertimbangkan dalam improvement selanjutnya yap 🤩

**Comment by fjtiaratsalsa** [comment]
Halo kak untuk fee iklan per pesanan sudah ada di dokumentasi baru ya silakan cek kembali terima kasih
