### ISSUE TITLE
Required Information pada setiap game / kategori

### ISSUE THREAD

**Issue by apapedulimu** [FIVEJACK/itemku-seller-open-api#7]
Halo min, cara tau required information untuk setiap game gimana ya? misal di mobile legends ada player_id sama zone, kalau di freefire dan game lain bagaimana ya?

**Comment by fjtiaratsalsa** [comment]
Halo kak, untuk beberapa game sudah kami tambahkan di dokumentasi terbaru disini yap https://tokoku.itemku.com/open-api 

Semoga membantu 👍🙏

**Comment by apapedulimu** [comment]
@fjtiaratsalsa sangat membantu banget kak, terimakasih banyak. Kalau untuk pulsa dan utilitas nomor telponnya parameternya apa ya kak? masih player_id kah?

Terimakasih.

**Comment by fjtiaratsalsa** [comment]
untuk pulsa dan beberapa yang belum termasuk, tidak ada pemisahan player_id kak langsung value nya saja yap

kami akan coba consider di next improvement untuk penambahan API listsnya juga ya kak, terima kasih

**Comment by apapedulimu** [comment]
Baik Kak, Terimakasih Banyak atas jawabannya. Saya izin close issue ini ya. Terimakasih Banyak @fjtiaratsalsa
