### ISSUE TITLE
API ITEMKU TIDAK RESPOND

### ISSUE THREAD

**Issue by ekonetworks** [FIVEJACK/itemku-seller-open-api#8]
halo ini ada orderan tapi ga keterima api itemku nya jadi ga proses otomatis
![Screenshot_20231217-193643_Chrome](https://github.com/FIVEJACK/itemku-seller-open-api/assets/154108961/fed4e3b4-c517-455a-b5d0-3c6a72e749f2)

**Comment by fjtiaratsalsa** [comment]
Halo kak ada detail endpoint yang bermasalah untuk di share?

**Comment by fjtiaratsalsa** [comment]
Halo kak, untuk pertanyaan direct ke seller aku bantu help di discord ya

**Comment by ekonetworks** [comment]
> Halo kak ada detail endpoint yang bermasalah untuk di share?

nanti saya tanya developer saya dlu

**Comment by axiecomunistream2** [comment]
halo saya developer eko, saya sudah cek sistem penerima api kami menggunakan postman dan memang sistem kami tanpa masalah.
selain itu di sistem api kami,jika ada json yang terkirim akan selalu di log dahulu,tapi tidak ada masuk json dari itemku.

yang bermasalah adalah order callback dari itemku ketika ada orderan masuk.

**Comment by fjtiaratsalsa** [comment]
Halo kak, seperti yang sudah kita share di discord ketika kita HIT ke API callback dari log kita menemukan response error dari API milik seller pada order number tersebut, detail error kami kirim ke discord ya kak

Karena mendapatkan error tersebut, callback dari itemku tidak berhasil masuk ke API yang seller miliki. Seperti di dokumentasi, untuk sekarang itemku tidak melakukan proses retry ketika hit api seller. Kita ada opsi lain supaya seller bisa check pesanan baru dari api order lists kita juga ya kak :)

**Comment by axiecomunistream2** [comment]
mungkin kemarin server saya sedang down. jadi mohon tetap lanjutkan hit ketika ada order ya. karena sejak error itu,tidak ada lagi hit masuk ke api kami. barusan saya sudah cek api kami sudah aktif

**Comment by ekonetworks** [comment]
> Halo kak, seperti yang sudah kita share di discord ketika kita HIT ke API callback dari log kita menemukan response error dari API milik seller pada order number tersebut, detail error kami kirim ke discord ya kak
> 
> Karena mendapatkan error tersebut, callback dari itemku tidak berhasil masuk ke API yang seller miliki. Seperti di dokumentasi, untuk sekarang itemku tidak melakukan proses retry ketika hit api seller. Kita ada opsi lain supaya seller bisa check pesanan baru dari api order lists kita juga ya kak :)

haloo updatenya ini gimana?

**Comment by fjtiaratsalsa** [comment]
Halo kak terkait issue yang ada di Callback, dari kakak bisa minta log dengan pesanan terkait ke discord ya kak nanti kita akan bantu cek dari log pesanan tersebut

Semoga membantu ya kak @ekonetworks

**Comment by fjtiaratsalsa** [comment]
Halo kak saya izin close issue ini ya, jika masih ada issue kakak bisa create new issue kembali. Terima kasih 😁
